" Basic settings 
"---------------------------------------------------------------
"
" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim
"
" Set vim not to act like vi (predecessor)
set nocompatible
" Source local vimrc if present
augroup vimrc
    au!
    au bufwritepost ~/.vim/vimrc source $MYVIMRC
augroup END
"
" Set viminfo file for bigger buffer size
" Also saves copied text between sessions
set viminfo='100,<1000,s100
"
" Set leader key to ','
:let mapleader=","
"
" Visual Customization 
"---------------------------------------------------------------
"
" Jump to the last position when reopening a file
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
"
" General settings
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)
"
" Enable indentation by file type
filetype plugin indent on
"
" Syntax highlighting
syntax enable
"
" Set background to dark
set background=dark
"
" Set line number vs relative auto switch
set number relativenumber
"
" Set changing line numbers when in insert mode
augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
"
" Always show file path
set laststatus=2
set statusline+=%F
"
" Filetype specifiic settings 
"---------------------------------------------------------------
"
" Recognize file types
au Bufread,BufNewFile *.tikz setfiletype tex
au Bufread,BufNewFile *.sage setfiletype python
au Bufread,BufNewFile *.py   setfiletype python
au BufNewFile,BufRead *.md,* setfiletype markdown
"
" Replace tab by spaces + specific file types
set tabstop=4 | set shiftwidth=4 | set expandtab
autocmd filetype tex set tabstop=2 | set shiftwidth=2
autocmd filetype cpp set tabstop=2 | set shiftwidth=2
autocmd Filetype make setlocal noexpandtab
"
" Find command settings
"---------------------------------------------------------------
"
" Search down into subfolders
" Provide tab-completion for all file-related tasks
set path+=**
"
" Show command line autocomplete choices above command line
set wildmenu
"
" Tag jumping setup
"---------------------------------------------------------------
"
" Create the 'tags' file (ctags needs to be installed first)
command! MakeTags !ctags -R .
"
" NOW WE CAN:
" - Use ^] to jump to tag under cursor
" - Use g^] for ambiguous tags (produces liste)
" - Use ^t to jump back up the tag stack
"
"
" Vim native autocomplete
"---------------------------------------------------------------
" The good stuff is documented in |ins-completion|
"
" HIGHLIGHTS:
" - ^x^n for JUST this file
" - ^x^f for filenames (works with our path trick!)
" - ^x^] for tags only
" - ^n for anything specified by the 'complete' option
"
